version: '3'

services:
  data_source:
    image: postgres:latest
    container_name: pacbook-src
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USER=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./helper/src_data:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data

  data_warehouse:
    image: postgres:latest
    container_name: pacbook-dwh
    environment:
      - POSTGRES_DB=${DWH_POSTGRES_DB}
      - POSTGRES_USER=${DWH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DWH_POSTGRES_PASSWORD}
    ports:
      - ${DWH_POSTGRES_PORT}:5432
    volumes:
      - ./helper/dwh_data:/docker-entrypoint-initdb.d
      - dwh-volume:/var/lib/postgresql/data

volumes:
  source-volume:
  dwh-volume: